workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "publish" && $CI_PIPELINE_SOURCE == "push"

deploy:
  image: azul/zulu-openjdk-alpine:11.0.23-jdk
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  before_script:
    - chmod +x ./gradlew
  script:
    - 'gradle publish'
